### ISSUE TITLE
Handle "process with pid ... still holds the lock"

### ISSUE THREAD

**Issue by probonopd** [helloSystem/Utilities#95]
Handle

```
process with pid 2681 still holds the lock

process with pid 2681 still holds the lock

process with pid 2681 still holds the lock
```

by setting the progress bar to indeterminate. (This can be simulated by `pkg install xvier` and then idling on `Proceed with this action? [y/N]` and then trying to install e.g., Audacity from the menu.)

**Comment by CocoCR300** [comment]
I think it is needed to check if the lock is held before the installation because, at least for me, only a few of those messages are outputted by `pkg` before stopping, so right now it would be needed to rerun the command every time it stops. The way I've found of checking the lock is to use `pkg shell` and read the `pkg_lock` or `pkg_lock_pid` tables.

**Comment by CocoCR300** [comment]
But where is the `app-placeholder` file? It is not in this repository
